Level 3
marmos91/interns-training pull request #49
Opened 2020-09-22 07:06 UTC by MaximKalinin

2020-09-22 08:03 UTC, Pigotz requested changes

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +        this._socket.on('message', this._onMessage);
New line :see_no_evil:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +        this._socket.close(callback);
New line :see_no_evil:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _onMessage(buffer: Buffer, rinfo: dgram.AddressInfo)
:snake:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _addClient(message: IMessage, address: Address)
:snake:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +        if (this._clients[id])
New line :see_no_evil:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +        this._clients[id] = {id, username, address};
New line :see_no_evil:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _sendMessage(message: IMessage)
:snake:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +        if (!client)
New line :see_no_evil:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +        const {address: {ip, port}} = client;
New line :see_no_evil:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _removeClient(message: IMessage)
:snake:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _broadcast(message: IMessage)
Missing return type

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _removeClient(message: IMessage)
Missing return type

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _sendMessage(message: IMessage)
Missing return type

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _addClient(message: IMessage, address: Address)
Missing return type

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +        switch (message.type)
New line :see_no_evil:

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    private _onMessage(buffer: Buffer, rinfo: dgram.AddressInfo)
Missing return type

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    shutdown(callback?: () => void)
Missing return type

2020-09-22 08:03 UTC, Pigotz commented on src/Server.ts
> +    async listen(port?: number | ((port: number) => void), callback?: (port: number) => void)
Missing return type

2020-09-22 09:20 UTC, MaximKalinin commented on src/Client.ts
> +export default class
name of the class?

2020-09-22 09:20 UTC, MaximKalinin commented on src/Client.ts
> +        this._server = server;
after `const {port, ip} = server;`?

2020-09-22 12:48 UTC, Pigotz commented on src/Client.ts
> +export default class
I think `Client` could be a good name

2020-09-22 12:50 UTC, Pigotz commented on src/Client.ts
> +        this._server = server;
Yes, I didn't specify

2020-09-22 12:58 UTC, Pigotz requested changes
Now it's better but there are some comments still open. Also, in the last review I completely missed the fact that the `Client` class has no member access modifiers. Please, specify them :+1:

2020-09-23 15:02 UTC, MaximKalinin commented on src/Client.ts
> +export default class
Changed😉

2020-09-23 15:02 UTC, MaximKalinin commented on src/Server.ts
> +class Server
Changed 😉

2020-09-24 07:40 UTC, Pigotz approved these changes
:+1:

2020-09-24 09:13 UTC, closed without merging